# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\admin\Desktop\bottle_guessing_game\bottle_game_design.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(624, 450)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 181, 451))
        self.frame.setStyleSheet("\n"
"background-color: rgb(47, 158, 151);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(40, 20, 91, 41))
        self.label.setStyleSheet("font: 18pt \"Tahoma\";\n"
"color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(30, 60, 111, 41))
        self.label_2.setStyleSheet("font: 18pt \"Tahoma\";\n"
"color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(50, 100, 61, 41))
        self.label_3.setStyleSheet("font: 18pt \"Tahoma\";\n"
"color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.line = QtWidgets.QFrame(self.frame)
        self.line.setGeometry(QtCore.QRect(0, 190, 181, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.btn_easy = QtWidgets.QCommandLinkButton(self.frame)
        self.btn_easy.setGeometry(QtCore.QRect(0, 200, 181, 51))
        self.btn_easy.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_easy.setStyleSheet("background-color: rgba(32, 98, 98, 100);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 10pt \"Tahoma\";\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:\\Users\\admin\\Desktop\\bottle_guessing_game\\bottle_question_mark.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_easy.setIcon(icon)
        self.btn_easy.setIconSize(QtCore.QSize(30, 30))
        self.btn_easy.setObjectName("btn_easy")
        self.btn_average = QtWidgets.QCommandLinkButton(self.frame)
        self.btn_average.setGeometry(QtCore.QRect(0, 260, 181, 51))
        self.btn_average.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_average.setStyleSheet("background-color: rgba(32, 98, 98, 100);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 10pt \"Tahoma\";\n"
"")
        self.btn_average.setIcon(icon)
        self.btn_average.setIconSize(QtCore.QSize(30, 30))
        self.btn_average.setObjectName("btn_average")
        self.btn_hard = QtWidgets.QCommandLinkButton(self.frame)
        self.btn_hard.setGeometry(QtCore.QRect(0, 320, 181, 51))
        self.btn_hard.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_hard.setStyleSheet("background-color: rgba(32, 98, 98, 100);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 10pt \"Tahoma\";\n"
"")
        self.btn_hard.setIcon(icon)
        self.btn_hard.setIconSize(QtCore.QSize(30, 30))
        self.btn_hard.setObjectName("btn_hard")
        self.line_2 = QtWidgets.QFrame(self.frame)
        self.line_2.setGeometry(QtCore.QRect(0, 370, 181, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_18 = QtWidgets.QLabel(self.frame)
        self.label_18.setGeometry(QtCore.QRect(10, 160, 161, 31))
        self.label_18.setStyleSheet("font: 10pt  \"Tahoma\";\n"
"\n"
"color: rgb(255, 255, 255);")
        self.label_18.setObjectName("label_18")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 631, 451))
        self.frame_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.lbl_question_number = QtWidgets.QLabel(self.frame_2)
        self.lbl_question_number.setGeometry(QtCore.QRect(190, 70, 231, 41))
        self.lbl_question_number.setStyleSheet("font: 14pt  \"Tahoma\";\n"
"color: rgb(0, 0, 0);")
        self.lbl_question_number.setObjectName("lbl_question_number")
        self.lbl_score = QtWidgets.QLabel(self.frame_2)
        self.lbl_score.setGeometry(QtCore.QRect(480, 70, 131, 41))
        self.lbl_score.setStyleSheet("font: 14pt  \"Tahoma\";\n"
"color: rgb(0, 0, 0);")
        self.lbl_score.setObjectName("lbl_score")
        self.txtedit_question = QtWidgets.QTextEdit(self.frame_2)
        self.txtedit_question.setGeometry(QtCore.QRect(210, 150, 371, 81))
        self.txtedit_question.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.txtedit_question.setReadOnly(True)
        self.txtedit_question.setObjectName("txtedit_question")
        self.frame_choose = QtWidgets.QFrame(self.frame_2)
        self.frame_choose.setGeometry(QtCore.QRect(210, 240, 371, 121))
        self.frame_choose.setStyleSheet("#frame_choose{\n"
"background-color: rgba(181, 181, 181,100);\n"
"}\n"
"#frame_choose:hover{\n"
"background-color: rgba(181, 181, 181,200);\n"
"\n"
"}\n"
"")
        self.frame_choose.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_choose.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_choose.setObjectName("frame_choose")
        self.chs_1 = QtWidgets.QRadioButton(self.frame_choose)
        self.chs_1.setGeometry(QtCore.QRect(10, 10, 351, 17))
        self.chs_1.setStyleSheet("background-color: rgba(24, 24, 24, 0);")
        self.chs_1.setObjectName("chs_1")
        self.chs_2 = QtWidgets.QRadioButton(self.frame_choose)
        self.chs_2.setGeometry(QtCore.QRect(10, 40, 351, 17))
        self.chs_2.setStyleSheet("background-color: rgba(24, 24, 24, 0);")
        self.chs_2.setObjectName("chs_2")
        self.chs_3 = QtWidgets.QRadioButton(self.frame_choose)
        self.chs_3.setGeometry(QtCore.QRect(10, 70, 351, 17))
        self.chs_3.setStyleSheet("background-color: rgba(24, 24, 24, 0);")
        self.chs_3.setObjectName("chs_3")
        self.btn_next = QtWidgets.QPushButton(self.frame_choose)
        self.btn_next.setGeometry(QtCore.QRect(290, 90, 75, 23))
        self.btn_next.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_next.setStyleSheet("background-color: rgb(25, 128, 217);\n"
"color: rgb(255, 255, 255);")
        self.btn_next.setObjectName("btn_next")
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setGeometry(QtCore.QRect(0, 380, 631, 61))
        self.frame_4.setStyleSheet("background-color: rgba(255, 0, 4, 100);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_14 = QtWidgets.QLabel(self.frame_4)
        self.label_14.setGeometry(QtCore.QRect(190, 0, 81, 31))
        self.label_14.setStyleSheet("font: 12pt  \"Tahoma\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgba(0, 0, 0,0);")
        self.label_14.setObjectName("label_14")
        self.lbl_answer2 = QtWidgets.QLabel(self.frame_4)
        self.lbl_answer2.setGeometry(QtCore.QRect(190, 30, 421, 31))
        self.lbl_answer2.setStyleSheet("font: 10pt  \"Tahoma\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgba(0, 0, 0,0);")
        self.lbl_answer2.setObjectName("lbl_answer2")
        self.btn_cancel = QtWidgets.QPushButton(self.frame_2)
        self.btn_cancel.setGeometry(QtCore.QRect(360, 120, 101, 23))
        self.btn_cancel.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_cancel.setStyleSheet("background-color: rgb(225, 42, 42);\n"
"color: rgb(255, 255, 255);")
        self.btn_cancel.setObjectName("btn_cancel")
        self.btn_next_question = QtWidgets.QPushButton(self.frame_2)
        self.btn_next_question.setGeometry(QtCore.QRect(470, 120, 101, 23))
        self.btn_next_question.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_next_question.setStyleSheet("background-color: rgb(25, 128, 217);\n"
"color: rgb(255, 255, 255);\n"
"")
        self.btn_next_question.setObjectName("btn_next_question")
        self.frame_correct = QtWidgets.QFrame(self.frame_2)
        self.frame_correct.setGeometry(QtCore.QRect(0, 380, 631, 61))
        self.frame_correct.setStyleSheet("background-color: rgba(0, 116, 85, 100);")
        self.frame_correct.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_correct.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_correct.setObjectName("frame_correct")
        self.label_16 = QtWidgets.QLabel(self.frame_correct)
        self.label_16.setGeometry(QtCore.QRect(190, 0, 81, 31))
        self.label_16.setStyleSheet("font: 12pt  \"Tahoma\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgba(0, 0, 0,0);")
        self.label_16.setObjectName("label_16")
        self.lbl_answer1 = QtWidgets.QLabel(self.frame_correct)
        self.lbl_answer1.setGeometry(QtCore.QRect(190, 30, 421, 31))
        self.lbl_answer1.setStyleSheet("font: 10pt  \"Tahoma\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgba(0, 0, 0,0);")
        self.lbl_answer1.setObjectName("lbl_answer1")
        self.frame_choose_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_choose_3.setGeometry(QtCore.QRect(0, 0, 631, 61))
        self.frame_choose_3.setStyleSheet("background-color: rgb(236, 236, 236);")
        self.frame_choose_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_choose_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_choose_3.setObjectName("frame_choose_3")
        self.lbl_mode = QtWidgets.QLabel(self.frame_choose_3)
        self.lbl_mode.setGeometry(QtCore.QRect(190, 10, 141, 41))
        self.lbl_mode.setStyleSheet("font: 18pt \"Tahoma\";\n"
"color: rgb(0, 0, 0);")
        self.lbl_mode.setObjectName("lbl_mode")
        self.btn_exit = QtWidgets.QCommandLinkButton(self.frame_choose_3)
        self.btn_exit.setGeometry(QtCore.QRect(510, 10, 101, 41))
        self.btn_exit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_exit.setStyleSheet("background-color: rgba(255, 0, 4,100);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 10pt \"Tahoma\";\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("C:\\Users\\admin\\Desktop\\bottle_guessing_game\\exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_exit.setIcon(icon1)
        self.btn_exit.setIconSize(QtCore.QSize(25, 25))
        self.btn_exit.setObjectName("btn_exit")
        self.frame_choose_3.raise_()
        self.lbl_question_number.raise_()
        self.lbl_score.raise_()
        self.txtedit_question.raise_()
        self.frame_choose.raise_()
        self.frame_4.raise_()
        self.btn_cancel.raise_()
        self.btn_next_question.raise_()
        self.frame_correct.raise_()
        self.frame_2.raise_()
        self.frame.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Bottle Guessing Game"))
        self.label.setText(_translate("MainWindow", "BOTTLE"))
        self.label_2.setText(_translate("MainWindow", "GUESSING"))
        self.label_3.setText(_translate("MainWindow", "GAME"))
        self.btn_easy.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#4f4f4f;\">Click for an easy mode questions</span></p></body></html>"))
        self.btn_easy.setText(_translate("MainWindow", "Bottle 1 (Easy)"))
        self.btn_average.setToolTip(_translate("MainWindow", "Click for an average mode questions"))
        self.btn_average.setText(_translate("MainWindow", "Bottle 2 (Average)"))
        self.btn_hard.setToolTip(_translate("MainWindow", "Click for an hard mode questions"))
        self.btn_hard.setText(_translate("MainWindow", "Bottle 3 (Hard)"))
        self.label_18.setText(_translate("MainWindow", "Choose difficulty to Start"))
        self.lbl_question_number.setText(_translate("MainWindow", "QUESTION NUMBER: "))
        self.lbl_score.setText(_translate("MainWindow", "SCORE:"))
        self.txtedit_question.setToolTip(_translate("MainWindow", "question"))
        self.txtedit_question.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">HDFDFGDFGDFGDFSDFGDSFGGDDFG</p></body></html>"))
        self.chs_1.setToolTip(_translate("MainWindow", "option 1"))
        self.chs_1.setText(_translate("MainWindow", "Option 1"))
        self.chs_2.setToolTip(_translate("MainWindow", "option 2"))
        self.chs_2.setText(_translate("MainWindow", "Option 1"))
        self.chs_3.setToolTip(_translate("MainWindow", "option 3"))
        self.chs_3.setText(_translate("MainWindow", "Option 1"))
        self.btn_next.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#4f4f4f;\">click here to submit the answer</span></p></body></html>"))
        self.btn_next.setText(_translate("MainWindow", "Enter"))
        self.label_14.setText(_translate("MainWindow", "Wrong!"))
        self.lbl_answer2.setText(_translate("MainWindow", "Answer: lbl_answer2"))
        self.btn_cancel.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#4f4f4f;\">cancel mode</span></p></body></html>"))
        self.btn_cancel.setText(_translate("MainWindow", "Cancel"))
        self.btn_next_question.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#4f4f4f;\">next question/pass</span></p></body></html>"))
        self.btn_next_question.setText(_translate("MainWindow", "Next Question"))
        self.label_16.setText(_translate("MainWindow", "Correct!"))
        self.lbl_answer1.setText(_translate("MainWindow", "lbl_answer1"))
        self.lbl_mode.setText(_translate("MainWindow", "MODE: EASY"))
        self.btn_exit.setToolTip(_translate("MainWindow", "click here to exit the game"))
        self.btn_exit.setText(_translate("MainWindow", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
